services:
  api:
    image: ghcr.io/naqqosh/zehngoh-api:latest
    container_name: api
    env_file: ./env/api.env
    volumes:
      - "../seller-api:/seller-api:ro"
    networks:
      - db
      - app
      - external
    depends_on:
      - postgres
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

  ui:
    image: ghcr.io/naqqosh/zehngoh-ui:latest
    container_name: ui
    env_file: ./env/ui.env
    networks:
      - app
    depends_on:
      - api
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

  postgres:
    image: postgres:16
    container_name: postgresql
    env_file: ./env/pg.env
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    networks:
      - db
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
    networks:
      - app
      - external
    depends_on:
      - ui
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

volumes:
  pg_data:
    name: pg_data

networks:
  app:
    name: app_net
    internal: true

  db:
    name: db_net
    internal: true

  external:
    name: external_net
