services:
  api:
    image: ghcr.io/naqqosh/zehngoh-api:latest
    pull_policy: always
    container_name: api
    env_file: ./env/api.env
    volumes:
      - "../seller-api:/seller-api:ro"
    networks:
      - db
      - app
      - external
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:' + process.env.PORT + '/api/health', (res) => {process.exit(res.statusCode === 200 ? 0 : 1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

  ui:
    image: ghcr.io/naqqosh/zehngoh-ui:latest
    pull_policy: always
    container_name: ui
    env_file: ./env/ui.env
    networks:
      - app
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://127.0.0.1:' + process.env.PORT, (res) => {console.log(res.statusCode); process.exit(res.statusCode === 200 ? 0 : 1)}).on('error', (e) => {console.log(e.message), process.exit(1)})",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

  postgres:
    image: postgres:16
    container_name: postgresql
    env_file: ./env/pg.env
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    networks:
      - db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U myuser -d market_db -c 'SELECT 1' > /dev/null 2>&1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

  nginx:
    image: nginx:alpine
    container_name: nginx
    profiles: ["nginx"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "./nginx/fallback.html:/var/www/errors/fallback.html"
      - "/etc/nginx/ssl:/etc/nginx/ssl:ro"
    networks:
      - app
      - external
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "2"

volumes:
  pg_data:
    name: pg_data
    external: true

networks:
  app:
    name: app_net
    internal: true

  db:
    name: db_net
    # internal: true

  external:
    name: external_net
