server {
    listen 80;
    server_name api.zehngoh.uz;

    location /health {
        access_log off;
        return 200 '{"status":"ok"}';
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.zehngoh.uz;

    ssl_certificate     /etc/letsencrypt/live/api.zehngoh.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.zehngoh.uz/privkey.pem;

    # BLOCK SENSITIVE FILES
    location ~ /\.(env|git) {
        deny all;
    }

    location ~* /(vendor|phpunit|cgi-bin) {
        deny all;
    }

    location /health {
        access_log off;
        add_header Content-Type application/json;
        return 200 '{"status":"ok"}';
    }
    
    location / {
        proxy_pass http://api:3006;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}


server {
    listen 80;
    server_name zehngoh.uz www.zehngoh.uz;

    location /health {
        access_log off;
        return 200 '{"status":"ok"}';
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name zehngoh.uz www.zehngoh.uz;

    ssl_certificate     /etc/letsencrypt/live/zehngoh.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zehngoh.uz/privkey.pem;

    # BLOCK SENSITIVE FILES
    location ~ /\.(env|git) {
        deny all;
    }

    location ~* /(vendor|phpunit|cgi-bin) {
        deny all;
    }

    location /health {
        access_log off;
        add_header Content-Type application/json;
        return 200 '{"status":"ok"}';
    }

    location / {
        proxy_pass http://ui:3000;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 2s;
        proxy_read_timeout 5s;
        proxy_send_timeout 5s;

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;

        error_page 500 502 503 504 = /fallback.html;
    }

    location = /fallback.html {
        root /var/www/errors;
        internal;
    }
}

server {
    listen 80;
    server_name *.kamoliddin.uz;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name *.kamoliddin.uz;

    ssl_certificate     /etc/letsencrypt/live/kamoliddin.uz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kamoliddin.uz/privkey.pem;

    location / {
        proxy_pass http://localhost:YOUR_APP_PORT;
    }
}
